### ISSUE TITLE
Install ChatNow

### ISSUE THREAD

**Issue by ea4fvb** [thiagosf/chatNow#2]
Hello Thiago, seeing the quality of your projects I have decided to try your ChatNow, but I am not able to install it, any advice?

I download the project in the server I put the data of the database in chatNow / admin / app / config / conf_database.ini.php and I do not know where to go, I get an error 500

I tried to see the example of your website but the same thing happens

Thanks mate

**Comment by thiagosf** [comment]
Hello!

There was a conflit with Locale native class, I fixed this, please try again.

If persist error, add bellow line in `app/autoload.php`

```php
ini_set('display_errors', 1);
```

This project is very old, so maybe not work perfectly.

Good luck!

**Comment by ea4fvb** [comment]
Thanks Thiago I'll try

nice day
